dist: xenial
language: bash

script: 
  - cp a.txt a.txt.out  
  - printf "\nOUTPUT" >> a.txt.out
  - echo "sdsdjsqld" >> stuff.tmp

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  on:
    branch: master


